version: "3.1"

services:
  auth-services:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    ports:
      - "3001:3001"

  get-todolist-services:
    build:
      context: ./get-todolist-service
      dockerfile: Dockerfile
    environment:
      - PORT=3002
    ports:
      - "3002:3002"

  todolist-services:
    build:
      context: ./todolist-service
      dockerfile: Dockerfile
    environment:
      - PORT=3003
    ports:
      - "3003:3003"

  mongo:
    image: mongo
    container_name: network-microservices
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ./data:/data/db
