version: "3.1"

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://microservices-auth-services-1:3001
      - GET_TODOLIST_SERVICE_URL=http://microservices-get-todolist-services-1:3002
      - TODOLIST_SERVICE_URL=http://microservices-todolist-services-1:3003
    ports:
      - "3000:3000"

  auth-services:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - MONGOURI=mongodb://mongo:27017
    ports:
      - "3001:3001"

  get-todolist-services:
    build:
      context: ./get-todolist-service
      dockerfile: Dockerfile
    environment:
      - PORT=3002
      - MONGOURI=mongodb://mongo:27017
    ports:
      - "3002:3002"

  todolist-services:
    build:
      context: ./todolist-service
      dockerfile: Dockerfile
    environment:
      - PORT=3003
      - MONGOURI=mongodb://mongo:27017
    ports:
      - "3003:3003"

  mongo:
    image: mongo
    container_name: network-microservices
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ./data:/data/db
